explicit template

diff --git a/.github/workflows/test_action.yml b/.github/workflows/test_action.yml
--- a/.github/workflows/test_action.yml
+++ b/.github/workflows/test_action.yml
@@ -46,8 +46,13 @@ jobs:
       - name: Verify downloaded artifact
         run: |
           tree artifacts
-          [ ! -f "artifacts/marimushka/index.html" ] && exit 1
-          [ ! -f "artifacts/marimushka/notebooks/fibonacci.html" ] && exit 1
+
+          [ ! -f "artifacts/marimushka/index.html" ] && echo "❌ index.html missing" && exit 1
+          [ ! -f "artifacts/marimushka/notebooks/fibonacci.html" ] && echo "❌ fibonacci.html missing" && exit 1
+
+
+
+
   book:
     runs-on: ubuntu-latest
     needs: test-only-notebooks
@@ -66,6 +71,7 @@ jobs:
       - name: Verify downloaded artifact
         run: |
           tree artifacts
+
           [ ! -f "artifacts/marimushka/index.html" ] && exit 1
           [ ! -f "artifacts/marimushka/notebooks/fibonacci.html" ] && exit 1
 
